tls:
  stores:
    default:
#      defaultCertificate:
#        certFile: /etc/traefik/certs/default.crt
#        keyFile: /etc/traefik/certs/default.key
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      curvePreferences:
        - CurveP256
        - CurveP384
#      sniStrict: true
